[package]
name = "libaries"
version = "0.1.0"
authors = ["camiloparra <caeparra@gmail.com>"]
edition = "2018"

[dependencies]
rmp-serde = "0.13.7"
serde = "1.0.99"
serde_json = "1.0.40"
serde_derive = "1.0.99"
futures = "0.1.28"